name: Build, Publish, and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      PIPELINE_PAT: ${{ secrets.PIPELINE_PAT }}  # PAT with Read/Write/Delete/Repo
      GH_PERSONAL_PKG_RW_TOKEN: ${{ secrets.GH_PERSONAL_PKG_RW_TOKEN }}  # PAT with Publish npm packages
      DOCKER_IMAGE_NAME: shaazcs-manager-ui
      DOCKER_IMAGE_TAG: 1.0.0 # We can set this dynamically as needed
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.8.0'   # match your engines.node
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # -----------------------------
      # Setup Python
      # -----------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: pip install --upgrade pip && pip install requests
        
      # -----------------------------
      # Delete old NPM package (Python)
      # -----------------------------
      - name: Delete old npm package
        run: python scripts/delete_old_npm_pkg.py

      # -----------------------------
      # Publish New NPM package (Python)
      # -----------------------------
      - name: Publish New npm package
        run: python scripts/publish_new_pkg.py

      # -----------------------------
      # Docker Build (Python)
      # -----------------------------
      - name: Build Docker Image
        run: python scripts/docker_build.py

      # -----------------------------
      # Delete Old Docker Image (Python)
      # -----------------------------
      - name: Delete Old Docker Image
        run: python scripts/delete_old_docker_image.py

      # -----------------------------
      # Push Docker Image (Python)
      # -----------------------------
      - name: Push Docker Image
        run: python scripts/push_docker_image.py