name: Build, Publish, and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.8.0'   # match your engines.node
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # -----------------------------
      # 🔥 DELETE OLD NPM PACKAGE
      # -----------------------------
      - name: Delete old npm package version
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          echo "Deleting old versions of $PACKAGE_NAME from GitHub Packages..."
          VERSIONS_URL="https://api.github.com/users/${{ github.repository_owner }}/packages/npm/$PACKAGE_NAME/versions"
          curl -s -H "Authorization: Bearer ${{ secrets.PIPELINE_PAT }}" "$VERSIONS_URL" \
            | jq '.[].id' | while read id; do
              echo "Deleting package version id $id"
              curl -X DELETE -H "Authorization: Bearer ${{ secrets.PIPELINE_PAT }}" \
                "$VERSIONS_URL/$id"
            done

      # -----------------------------
      # 📦 PUBLISH NPM PACKAGE
      # -----------------------------
      - name: Publish npm package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PIPELINE_PAT }}

      # -----------------------------
      # 🧹 DELETE OLD GHCR IMAGE
      # -----------------------------
      - name: Delete old GHCR image version
        run: |
          REPO=${{ github.repository }}
          echo "Deleting old Docker image versions from GHCR for $REPO"
          VERSIONS_URL="https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/shaazcs-manager-ui/versions"
          curl -s -H "Authorization: Bearer ${{ secrets.PIPELINE_PAT }}" "$VERSIONS_URL" \
            | jq '.[].id' | while read id; do
              echo "Deleting image version id $id"
              curl -X DELETE -H "Authorization: Bearer ${{ secrets.PIPELINE_PAT }}" \
                "$VERSIONS_URL/$id"
            done

      # -----------------------------
      # 🐳 BUILD AND PUSH DOCKER IMAGE
      # -----------------------------
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:1.0.0
          echo ${{ secrets.PIPELINE_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
